// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIFa05uFiCcK1lPTGf80VtcltDf51IXB4',
    appId: '1:809881275893:web:8914a2400fc191524e24bc',
    messagingSenderId: '809881275893',
    projectId: 'smarthelmet-de844',
    authDomain: 'smarthelmet-de844.firebaseapp.com',
    storageBucket: 'smarthelmet-de844.appspot.com',
    measurementId: 'G-XP4JLXYJG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3s9YVIhLbWvoOONreaOEoIxsyUbUhGng',
    appId: '1:809881275893:android:0890f7a1e283163a4e24bc',
    messagingSenderId: '809881275893',
    projectId: 'smarthelmet-de844',
    storageBucket: 'smarthelmet-de844.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlqqC8gxtZp5P1SgioFGAQVp4gKb6F_Hs',
    appId: '1:809881275893:ios:01ff9c88182133344e24bc',
    messagingSenderId: '809881275893',
    projectId: 'smarthelmet-de844',
    storageBucket: 'smarthelmet-de844.appspot.com',
    iosClientId: '809881275893-pfqgttfd2i94pie290oq82271hmpv17j.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarthelmet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlqqC8gxtZp5P1SgioFGAQVp4gKb6F_Hs',
    appId: '1:809881275893:ios:01ff9c88182133344e24bc',
    messagingSenderId: '809881275893',
    projectId: 'smarthelmet-de844',
    storageBucket: 'smarthelmet-de844.appspot.com',
    iosClientId: '809881275893-pfqgttfd2i94pie290oq82271hmpv17j.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarthelmet',
  );
}
